--------------------------------------------------------
--  File created - Friday-April-06-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XMCGURF
--------------------------------------------------------

  CREATE TABLE "FIMSMGR"."XMCGURF" 
   (	"XMCGURF_TRANS_TYPE" VARCHAR2(2 CHAR), 
	"XMCGURF_BATCH" VARCHAR2(10 CHAR), 
	"XMCGURF_TRANS_DATE" DATE, 
	"XMCGURF_DESCRIPTION" VARCHAR2(35 CHAR), 
	"XMCGURF_AMOUNT" NUMBER(12,2), 
	"XMCGURF_DR_CR_IND" VARCHAR2(1 CHAR), 
	"XMCGURF_REF" VARCHAR2(8 CHAR), 
	"XMCGURF_INDEX" VARCHAR2(6 CHAR), 
	"XMCGURF_ACCOUNT" VARCHAR2(6 CHAR), 
	"XMCGURF_MISC" VARCHAR2(10 CHAR), 
	"XMCGURF_BANK" VARCHAR2(2 CHAR), 
	"XMCGURF_BATCH_FILE" VARCHAR2(30 CHAR), 
	"XMCGURF_ENTRY_DATE" DATE, 
	"XMCGURF_PROCESS_DATE" DATE, 
	"XMCGURF_RULE_DETAIL_CODE" VARCHAR2(4 CHAR), 
	"XMCGURF_ID" VARCHAR2(9 CHAR), 
	"XMCGURF_ACTIVITY" VARCHAR2(6 CHAR), 
	"XMCGURF_DOC_CODE" VARCHAR2(8 CHAR), 
	"XMCGURF_SEQ_NUM" NUMBER(8,0), 
	"XMCGURF_SURROGATE_ID" NUMBER(19,0), 
	"XMCGURF_VERSION" NUMBER(19,0), 
	"XMCGURF_USER_ID" VARCHAR2(30 CHAR), 
	"XMCGURF_DATA_ORIGIN" VARCHAR2(30 CHAR), 
	"XMCGURF_ACTIVITY_DATE" DATE, 
	"XMCGURF_VPDI_CODE" VARCHAR2(6 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DEVELOPMENT"  ENABLE ROW MOVEMENT ;

   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_SURROGATE_ID" IS 'SURROGATE ID: Immutable unique key';
   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_VERSION" IS 'VERSION: Optimistic lock token.';
   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_USER_ID" IS 'USER ID: The user ID of the person who inserted or last updated this record.';
   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_DATA_ORIGIN" IS 'DATA ORIGIN: Source system that created or updated the data.';
   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_ACTIVITY_DATE" IS 'ACTIVITY DATE: The date that information in this record was entered or last updated.';
   COMMENT ON COLUMN "FIMSMGR"."XMCGURF"."XMCGURF_VPDI_CODE" IS 'VPDI CODE: Multi-entity processing code.';
